version: "3.7"
services:
  api_service:
    build: .
    restart: always
    ports:
      - 8080:8080
    networks:
      - springapimysql_net
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/fintech?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
      - spring.datasource.username=root
      - spring.datasource.password=admin
    depends_on:
      - mysqldb
    volumes:
      - .m2:/root/.m2

  mysqldb:
    image: "mysql:8.0"
    restart: always
    networks:
      - springapimysql_net
    environment:
      MYSQL_ROOT_PASSWORD: admin
networks:
  springapimysql_net:
    driver: bridge
